### ISSUE TITLE
SELinux avc danied

### ISSUE THREAD

**Issue by ih24n69** [ih24n69/android_device_samsung_kanas#3]
On Resurrection Remix 5.7.2 android version 6.0.1.
Log error here : 
[RR-4-2.txt](https://github.com/ih24n69/android_device_samsung_kanas/files/640980/RR-4-2.txt)

**Comment by Rosalie241** [comment]
Same issue here, I know how to fix it though.

**Comment by ih24n69** [comment]
How?

**Comment by ih24n69** [comment]
all done. use permisive selinux
