### ISSUE TITLE
Missing sec_format.h

### ISSUE THREAD

**Issue by k3rnelpanic** [ih24n69/android_device_samsung_kanas#4]
Missing some file called sec_format h 

frameworks/av/media/libstagefright/ACodec.cpp:44:24: fatal error: sec_format.h: No such file or directory
compilation terminated.
build/core/binary.mk:432: recipe for target '/home/bayu/android/lineage/out/target/product/kanas/obj/SHARED_LIBRARIES/libstagefright_intermediates/ACodec.o' failed
make: *** [/home/bayu/android/lineage/out/target/product/kanas/obj/SHARED_LIBRARIES/libstagefright_intermediates/ACodec.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by ih24n69** [comment]
you forget hardware_samsung package

**Comment by k3rnelpanic** [comment]
oh you're right, im forget
